### ISSUE TITLE
Data store contents?

### ISSUE THREAD

**Issue by RobertCalise** [zippopotamus/zippopotamus#16]
@trea Is there a current data dump to use for local testing/developing improvements? All I can seem to find is https://github.com/crowell/Zippopotamus, but it's incomplete.

**Comment by Jogai** [comment]
The original branch has a link, see https://github.com/samirahmed/Zippopotamus-Cloud/commit/c1ded1d2e6eee02dd45e255534bb41b94c1002a8

**Comment by gyroscopes** [comment]
The database is under the Open Database License. But no link !
Not very open.
