### ISSUE TITLE
Brazil Postal Codes

### ISSUE THREAD

**Issue by bngoofy** [zippopotamus/zippopotamus#32]
Hello,

Trying to use the api for Brazil Postal Codes but I can't get it to work. Using the api.zippopotam.us/BR/01000-000 sample, I tried api.zippopotam.us/BR/31035-460 and other postal codes and could not get a result. Thank you for any assistance.

**Comment by trea** [comment]
Hello @bngoofy,

I've taken a quick look into this issue for you.  Our data comes from GeoNames, and as part of their data, there is this notice:

> For Brazil only major postal codes are available (only the codes ending with -000 and the major code per municipality).

To test that, I tried the major code for Rio de Janeiro and got a response (http://api.zippopotam.us/br/20000-000).  So outside of looking up major postal codes, my guess is that Zippopotam.us is not going to be a great fit for you.

Please let me know if I can help further.

Thanks!

**Comment by gyroscopes** [comment]
If zippopotam.us is unrealiable or out-of-date for a certain country, that country should be removed or at least a warning issued for that country.
