### ISSUE TITLE
API for country 'US' is blocked in countries

### ISSUE THREAD

**Issue by jamesoquendo** [zippopotamus/zippopotamus#71]
The API call with country 'US' api.zippopotam.us/us/postal-code returns a 404 if I VPN to other counties. This was first noted by a QA team member in India. Any workaround when testing US form fills from other countries?

**Comment by trea** [comment]
Examples of requests and responses would be very helpful if you could get them please. I think the only thing in the way here might be the CDN/WAF in front of the API, I'm not intentionally blocking access from VPNs or other countries, but I won't be able to help diagnose without more detail.

**Comment by jamesoquendo** [comment]
We haven't experienced this issue since so closing the issue. Thank you.
